# Generated by Django 3.1.7 on 2021-03-15 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='0710663922', max_length=32, unique=True),
            preserve_default=False,
        ),
    ]
